Buildings = [
	    ["Arkham Horror", "Ye Olde Magick Shoppe", True, "Uptown"], 
	    ["Arkham Horror", "Woods", False, "Uptown"],
	    ["Arkham Horror", "Velma's Diner", True, "Easttown"],
	    ["Arkham Horror", "Unvisited Isle", False, "Merchant District"],
	    ["Arkham Horror", "Train Station", True, "Northside"],
	    ["Arkham Horror", "The Witch House", False, "French Hill"],
	    ["Arkham Horror", "The Unnamable", False, "Merchant District"],
	    ["Arkham Horror", "St. Mary's Hospital", True, "Uptown"],
	    ["Arkham Horror", "South Church", True, "Southside"],
	    ["Arkham Horror", "Silver Twilight Lodge", False, "French Hill"],
	    ["Arkham Horror", "Science Building", False, "Miskatonic University"],
	    ["Arkham Horror", "River Docks", True, "Merchant District"],
	    ["Arkham Horror", "Police Station", True, "Easttown"],
	    ["Arkham Horror", "Newspaper", True, "Northside"],
	    ["Arkham Horror", "Ma's Boarding House", True, "Southside"],
	    ["Arkham Horror", "Library", True, "Miskatonic University"],
	    ["Arkham Horror", "Inner Sanctum", True, "French Hill"],
	    ["Arkham Horror", "Independence Square", False, "Downtown"],
	    ["Arkham Horror", "Administration Building", True, "Miskatonic University"],
	    ["Arkham Horror", "Arkham Asylum", True, "Downtown"],
	    ["Arkham Horror", "Bank of Arkham", True, "Downtown"],
	    ["Arkham Horror", "Black Cave", False, "Rivertown"],
	    ["Arkham Horror", "Curiositie Shoppe", True, "Northside"],
	    ["Arkham Horror", "General Store", True, "Rivertown"],
	    ["Arkham Horror", "Graveyard", False, "Rivertown"],
	    ["Arkham Horror", "Hibb's Roadhouse", False, "Easttown"],
	    ["Arkham Horror", "Historical Society", False, "Southside"]
	]

Streets = [
	    ["Arkham Horror", "Northside"],
	    ["Arkham Horror", "Downtown"],
	    ["Arkham Horror", "Easttown"],
	    ["Arkham Horror", "Rivertown"],
	    ["Arkham Horror", "Miskatonic University"],
	    ["Arkham Horror", "French Hill"],
	    ["Arkham Horror", "Uptown"],
	    ["Arkham Horror", "Southside"],
	    ["Arkham Horror", "Merchant District"],
	]

connections = [
	    ["Ye Olde Magick Shoppe", {"Uptown" : ['black', 'white', 'investigator'] }], 
	    ["Woods", {"Uptown" : ['black', 'white', 'investigator'] }],
	    ["Velma's Diner", {"Easttown" : ['black', 'white', 'investigator'] }],
	    ["Unvisited Isle", {"Merchant District" : ['black', 'white', 'investigator'] }],
	    ["Train Station", {"Northside" : ['black', 'white', 'investigator'] }],
	    ["The Witch House", {"French Hill" : ['black', 'white', 'investigator'] }],
	    ["The Unnamable", {"Merchant District" : ['black', 'white', 'investigator'] }],
	    ["St. Mary's Hospital", {"Uptown" : ['black', 'white', 'investigator'] }],
	    ["South Church", {"Southside" : ['black', 'white', 'investigator'] }],
	    ["Silver Twilight Lodge", {"French Hill" : ['black', 'white', 'investigator'] }],
	    ["Science Building", {"Miskatonic University" : ['black', 'white', 'investigator'] }],
	    ["River Docks", {"Merchant District" : ['black', 'white', 'investigator'] }],
	    ["Police Station", {"Easttown" : ['black', 'white', 'investigator'] }],
	    ["Newspaper", {"Northside" : ['black', 'white', 'investigator'] }],
	    ["Ma's Boarding House", {"Southside" : ['black', 'white', 'investigator'] }],
	    ["Library", {"Miskatonic University" : ['black', 'white', 'investigator'] }],
	    ["Inner Sanctum", {"French Hill" : ['black', 'white', 'investigator'] }],
	    ["Independence Square", {"Downtown" : ['black', 'white', 'investigator'] }],
	    ["Administration Building", {"Miskatonic University" : ['black', 'white', 'investigator'] }],
	    ["Arkham Asylum", {"Downtown" : ['black', 'white', 'investigator'] }],
	    ["Bank of Arkham", {"Downtown" : ['black', 'white', 'investigator'] }],
	    ["Black Cave", {"Rivertown" : ['black', 'white', 'investigator'] }],
	    ["Curiositie Shoppe", {"Northside" : ['black', 'white', 'investigator'] }],
	    ["General Store", {"Rivertown" : ['black', 'white', 'investigator'] }],
	    ["Graveyard", {"Rivertown" : ['black', 'white', 'investigator'] }],
	    ["Hibb's Roadhouse", {"Easttown" : ['black', 'white', 'investigator'] }],
	    ["Historical Society", {"Southside" : ['black', 'white', 'investigator'] }],
	    ["Northside", {"Newspaper" : ['investigator'], "Train Station" : ['investigator'], "Curiositie Shoppe" : ['investigator'], "Downtown" : ['white', 'investigator'], "Merchant District" : ['black', 'investigator'] }],
	    ["Downtown", {"Independence Square" : ['investigator'], "Arkham Asylum" : ['investigator'], "Bank of Arkham" : ['investigator'], "Merchant District": ['investigator'], "Easttown" : ['white', 'investigator'], "Northside" : ['black', 'investigator'] }],
	    ["Easttown", {"Velma's Diner" : ['investigator'], "Police Station" : ['investigator'], "Hibb's Roadhouse" : ['investigator'], "Rivertown" : ['white', 'investigator'], "Downtown" : ['black', 'investigator'] }],
	    ["Rivertown", {"Graveyard" : ['investigator'], "General Store" : ['investigator'], "Black Cave" : ['investigator'], "Merchant District": ['investigator'], "French Hill" : ['white', 'investigator'], "Easttown" : ['black', 'investigator'] }],
	    ["Miskatonic University", {"Library" : ['investigator'], "Administration Building" : ['investigator'], "Science Building" : ['investigator'], "Merchant District" : ['white', 'investigator'], "Uptown" : ['black', 'investigator'] }],
	    ["French Hill", {"The Witch House" : ['investigator'], "Silver Twilight Lodge" : ['investigator'], "Southside" : ['white', 'investigator'], "Rivertown" : ['black', 'investigator'] }],
	    ["Uptown", {"Ye Olde Magick Shoppe" : ['investigator'], "St. Mary's Hospital" : ['investigator'], "Woods" : ['investigator'], "Miskatonic University" : ['white', 'investigator'], "Southside" : ['black', 'investigator'] }],
	    ["Southside", {"Historical Society" : ['investigator'], "South Church" : ['investigator'], "Ma's Boarding House" : ['investigator'], "Uptown" : ['white', 'investigator'], "French Hill" : ['black', 'investigator'] }],
	    ["Merchant District", {"Unvisited Isle" : ['investigator'], "The Unnamable" : ['investigator'], "River Docks" : ['investigator'], "Downtown": ['investigator'], "Rivertown": ['investigator'], "Northside" : ['white', 'investigator'], "Miskatonic University" : ['black', 'investigator'] }],
	]

Investigatordata = [
		["Agnes", "Baker", "Waitress", "Velma's Diner", 5, 5, 2],
		["\"Ashcan\"", "Pete", "Drifter", "River Docks", 4, 6, 1],
		["Jenny", "Barnes", "Dilettante", "Train Station", 6, 4, 1],
		["Harvey", "Walters", "Professor", "Administration Building", 7, 3, 2],
	]

Otherworlds = [
	    ["Arkham Horror", "Another Dimension", ["Blue", "Green", "Red", "Yellow"]],
	    ["Arkham Horror", "Great Hall of Celano", ["Blue", "Green"]],
	    ["Arkham Horror", "Plateau of Leng", ["Green", "Red"]],
	    ["Arkham Horror", "R'lyeh", ["Red", "Yellow"]],
	    ["Arkham Horror", "The Abyss", ["Blue","Red"]],
	    ["Arkham Horror", "City of the Great Race", ["Green", "Yellow"]],
	    ["Arkham Horror", "The Dreamlands", ["Blue", "Green", "Red", "Yellow"]],
	    ["Arkham Horror", "Yuggoth", ["Blue", "Yellow"]]
	]



monsters = [
	    ['Mi-Go', 'Arkham Horror', 'Blue', [True, False, False, False, False, False, False, False, False], None, 1, -2, -1, 2, 0, 1, [None, None, None, None, None, None, None, None]] ,
	    ['Maniac', 'Arkham Horror', 'Black', [False, False, True, False, False, False, False, False, False], None, 1, -1, None, None, 1, 1, [None, None, None, None, None, None, None, None]] ,
	    ['Nightgaunt', 'Arkham Horror', 'Blue', [False, False, False, False, False, False, False, True, False], None, 2, -2, -1, 1, -2, None, [None, None, None, None, None, None, None, None]] ,
	    ['Shoggoth', 'Arkham Horror', 'Red', [False, False, False, False, False, True, False, False, False], None, 3, -1, -1, 3, -1, 3, 1, [None, False, None, None, None, None, None, None]] ,
	    ['Star Spawn', 'Arkham Horror', 'Black', [False, False, False, False, False, False, False, False, True], None, 3, -1, -3, 2, -3, 3, [None, None, None, None, None, None, None, None]] ,
	    ['The Black Man', 'Arkham Horror', 'Black', [False, False, True, False, False, False, False, False, False], 'Mask', 1, -3, None, None, None, None, [None, None, None, None, None, None, True, None]] ,
	    ['The Bloated Woman', 'Arkham Horror', 'Black', [False, False, False, True, False, False, False, False, False], 'Mask', 2, -1, -1, 2, -2, 2, [None, None, None, None, None, None, True, None]] ,
	    ['The Dark Pharaoh', 'Arkham Horror', 'Black', [False, False, False, False, False, False, False, True, False], 'Mask', 2, -1, -1, 1, -3, 3, [None, None, None, None, None, None, True, None]] ,
	    ['Vampire', 'Arkham Horror', 'Black', [False, False, True, False, False, False, False, False, False], 'Undead', 2, -3, 0, 2, -3, 3, None, [None, False, None, None, None, None, None, None]] ,
	    ['Warlock', 'Arkham Horror', 'Yellow', [True, False, False, False, False, False, False, False, False], None, 2, -2, -1, 1, -3, 1, None, [None, None, True, None, None, None, None, None]] ,
	    ['Witch', 'Arkham Horror', 'Black', [True, False, False, False, False, False, False, False, False], None, 1, -1, None, None, -3, 2, [None, None, None, False, None, None, None, None]] ,
	    ['Zombie', 'Arkham Horror', 'Black', [False, False, True, False, False, False, False, False, False], 'Undead', 1, 1, -1, 1, -1, 2, [None, None, None, None, None, None, None, None]] ,
	    ['Byakhee', 'Arkham Horror', 'Blue', [True, False, False, False, False, False, False, False, False], None, 1, -2, -1, 1, 0, 2, [None, None, None, None, None, None, None, None]] ,
	    ['Chthonian', 'Arkham Horror', 'Green', [False, True, False, False, False, False, False, False, False], None, 3, 1, -2, 2, -3, 3, [None, None, None, None, None, None, None, None]] ,
	    ['Cultist', 'Arkham Horror', 'Black', [False, False, True, False, False, False, False, False, False], None, 1, -3, None, None, 1, 1, [None, None, None, None, None, None, None, None]] ,
	    ['Dark Young', 'Arkham Horror', 'Yellow', [False, False, False, True, False, False, False, False, False], None, 3, -2, 0, 3, -1, 3, 1, [None, False, None, None, None, None, None, None]] ,
	    ['Dhole', 'Arkham Horror', 'Black', [True, False, False, False, False, False, False, False, False], None, 3, -1, 4, -3, -3, 4, 1, 1, [False, False, None, None, None, None, None, None]] ,
	    ['Dimensional Shambler', 'Arkham Horror', 'Red', [False, False, False, False, True, False, False, False, False], None, 1, -3, -2, 1, -2, None, [None, None, None, None, None, None, None, None]] ,
	    ['Elder Thing', 'Arkham Horror', 'Black', [False, False, False, False, False, True, False, False, False], None, 2, -2, -3, 2, 0, 1, [None, None, None, None, None, None, None, None]] ,
	    ['Fire Vampire', 'Arkham Horror', 'Blue', [False, False, False, False, False, False, True, False, False], None, 1, 0, None, None, -2, 2, [None, None, True, None, True, None, None, None]] ,
	    ['Flying Polyp', 'Arkham Horror', 'Blue', [False, False, False, True, False, False, False, False, False], None, 3, 0, -2, 4, -3, 3, [1, 1, False, None, None, None, None, None]],
	    ['Formless Spawn', 'Arkham Horror', 'Black', [False, False, False, True, False, False, False, False, False], None, 2, 0, -1, 2, -2, 2, [None, None, True, None, None, None, None, None]] ,
	    ['Ghost', 'Arkham Horror', 'Yellow', [False, False, True, False, False, False, False, False, False], 'Undead', 1, -3, -2, 2, -3, 2, [None, None, True, None, None, None, None, None]] ,
	    ['Ghoul', 'Arkham Horror', 'Black', [False, False, False, True, False, False, False, False, False], None, 1, -3, 0, 1, -1, 1, [None, None, None, None, True, None, None, None]] ,
	    ['God of the Bloody Tongue', 'Arkham Horror', 'Black', [False, True, False, False, False, False, False, False, False], 'Mask', 4, 1, -3, 3, -4, 4, [1, 1, None, None, None, None, True, None]] ,
	    ['Gug', 'Arkham Horror', 'Black', [False, False, False, False, False, False, False, True, False], None, 3, -2, -1, 2, -2, 4, None, [1, None, None, None, None, None, None, None]] ,
	    ['Haunter of the Dark', 'Arkham Horror', 'Blue', [False, False, False, False, True, False, False, False, False], 'Mask', 2, -3, -2, 2, -2, 2, [None, None, None, None, None, None, True, None]] ,
	    ['High Priest', 'Arkham Horror', 'Black', [False, False, False, False, False, False, False, False, True], None, 2, -2, 1, 1, -2, 2, None, [None, None, True, None, None, None, None, None]] ,
	    ['Hound of Tindalos', 'Arkham Horror', 'Green', [False, False, False, False, True, False, False, False, False], None, 2, -1, -2, 4, -1, 3, [None, None, True, None, None, None, None, None]] ,
	]




mythoscards = [
	    ['Big Storm Sweeps Arkham!', 'Arkham Horror', 'Headline', 'NULL', 'Independence Square', 'The Unnamable', [False, False, True, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, True], 'All monsters in the Sky and Outskirts are returned to the cup.'] ,
	    ['Bizarre Dreams Plague Citizens!', 'Arkham Horror', 'Headline', 'NULL', 'Science Building', 'The Witch House', [False, False, False, True, False, False, False, False, False], [False, True, False, False, False, False, True, True, False], 'All Gugs and Nightgaunts in Arkham are returned to the cup. If at least one monster returns to the cup, raise the terror level by 1.'] ,
	    ['Blackest Night', 'Arkham Horror', 'Environment', 'Mystic', 'Black Cave', "Hibb's Roadhouse", [False, False, False, False, True, True, False, False, False], [True, False, False, False, False, False, False, False, False], 'Luck checks in Arkham are made at a -1 penalty. Sneak checks in Arkham are made at a +1 bonus.'] ,
	    ['Blood Magic', 'Arkham Horror', 'Environment', 'Mystic', 'Independence Square', 'The Unnamable', [False, False, False, False, True, True, False, False, False], [True, False, False, False, False, False, False, False, False], 'Investigators who end their movement in Rivertown streets may choose to delve into dark mysteries using their life force. They roll dice equal to their current Stamina, and for every failed die, they lose 1 Stamina. If this reduces them to 0 Stamina, they are devoured and the player must start a new character. Otherwise, they gain 3 Clue tokens.'] ,
	    ['Blue Flu!', 'Arkham Horror', 'Headline', 'NULL', 'The Unnamable', 'Woods', [False, False, False, True, False, False, False, False, False], [False, True, False, False, False, False, True, True, False], 'All investigators in jail are released. No investigators may be arrested until the end of next turn. Leave this card in play until then to indicate this.'] ,
	    ['Campus Security Increased!', 'Arkham Horror', 'Headline', 'NULL', 'Independence Square', 'The Unnamable', [True, False, False, False, False, False, False, False, False], [False, False, False, False, True, True, False, False, False], 'All monsters in the Miskatonic U. Streets or Locations are returned to the cup.'] ,
	    ['Church Groep Reclaims Southside!', 'Arkham Horror', 'Headline', 'NULL', 'Black Cave', "Hibb's Roadhouse", [False, False, False, True, False, False, False, False, False], [False, True, False, False, False, False, True, True, False], 'All monsters in the Southside streets or locations are returned to the cup.'] ,
	    ['City Cripped by Blackouts!', 'Arkham Horror', 'Headline', 'NULL', 'Unvisited Isle', 'Science Building', [False, False, False, True, False, False, False, False, False], [False, True, False, False, False, False, True, True, False], 'The General Store, Curiositie Shoppe, and Ye Olde Magick Shoppe are closed until the end of next turn. Leave this card in play until then to indicate this.'] ,
	    ['Curfew Enforced', 'Arkham Horror', 'Environment', 'Urban', 'Unvisited Isle', 'Science Building', [False, False, False, False, False, False, False, False, True], [False, False, True, False, False, False, False, False, False], 'Any investigator who ends his movement in the streets must pass a Will (+0) check or be arrested and taken to the Police Station.'] ,
	    ["Darke's Carnival Arrives", 'Arkham Horror', 'Environment', 'Urban', 'The Unnamable', 'Woods', [False, False, False, False, True, True, False, False, False], [True, False, False, False, False, False, False, False, False], 'Investigators who end their movement in the Northside streets gain 1 Clue token from the sinister wonders they witness, but must pass a Will (-1) check or lose 1 Sanity.'] ,
	    ['Disturbing the Dead', 'Arkham Horror', 'Rumor', 'NULL', 'Black Cave', 'NULL', [False, True, False, False, False, False, True, True, False], [False, False, False, True, False, False, False, False, False], 'Ongoing Effect: Roll a die at the end of every Mythos Phase while this card is in play (beginning the turn after it entered play). On a 1 or 2, increase the terror level by 1. Pass: If a single player discards 2 gate trophies during the Arkham Encounter Phase while in the Rivertown streets, return this card to the box. Each player draws 1 Spell. Fail: If the terror level reaches 10, return this card to the box. Every investigator is Cursed. '] ,
	    ['Dreams of a Sunken City', 'Arkham Horror', 'Environment', 'Mystic', 'Independence Square', 'The Unnamable', [False, False, False, False, False, False, False, False, True], [False, False, True, False, False, False, False, False, False], 'Investigators cannot gain Sanity except by receiving psychiatric care at Arkham Asylum (or from Carolyn Fern).'] ,
	    ['Egyptian Exhibit Visits Miskantonic U.', 'Arkham Horror', 'Environment', 'Urban', 'The Witch House', 'Black Cave', [False, False, False, False, False, False, False, False, True], [False, False, True, False, False, False, False, False, False], 'Any investigator who ends his movement in the Miskatonic U. streets may pass a Lore (-1) check to gain 1 Clue token by reading the strange hieroglyphics on the artifacts in the exhibit.'] ,
	    ['Estate Sale', 'Arkham Horror', 'Environment', 'Urban', 'The Witch House', 'Black Cave', [False, False, False, False, True, True, False, False, False], [True, False, False, False, False, False, False, False, False], 'Investigators who end their movement in the Uptown streets may draw 2 Unique Items and purchase one, none, or both of them at list price, discarding any that are not purchased.'] ,
	    ['Family Found Butchered!', 'Arkham Horror', 'Headline', 'NULL', 'Graveyard', 'Unvisited Isle', [False, False, True, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, True], 'The terror level increases by 1 in light of this tragic news.'] ,
	    ['Feds Raid Arkham!', 'Arkham Horror', 'Headline', 'NULL', 'Black Cave', "Hibb's Roadhouse", [False, False, True, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, True], 'All monsters in the streets are returned to the cup.'] ,
	    ['Fourth of July Parade!', 'Arkham Horror', 'Headline', 'NULL', 'The Witch House', 'Black Cave', [False, False, True, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, True], 'Investigators cannot move into or out of the Merchant Dist. streets until the end of next turn. Leave this card in play until then to indicate this.'] ,
	    ['Gangs Clean Up Easttown!', 'Arkham Horror', 'Headline', 'NULL', 'The Witch House', 'Black Cave', [True, False, False, False, False, False, False, False, False], [False, False, False, False, True, True, False, False, False], 'All monsters in the Easttown streets or locations are returned to the cup.'] ,
	    ['Ghost Ship Docks by Itself!', 'Arkham Horror', 'Headline', 'NULL', 'The Unnamable', 'Woods', [False, False, True, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, True], 'An ancient ghost ship arrives in Arkham, releasing 2 monsters into the Merchant Dist. streets.'] ,
	    ['Goat-like Creature Spotted in Woods!', 'Arkham Horror', 'Headline', 'NULL', 'Independence Square', 'The Unnamable', [False, False, False, True, False, False, False, False, False], [False, True, False, False, False, False, True, True, False], 'All Dark Young in Arkham are returned to the cup. If at least one monster returns to the cup, raise the terror level by 1.'] ,
	    ['Good Work Undone', 'Arkham Horror', 'Rumor', 'NULL', 'Unvisited Isle', 'NULL', [False, True, False, False, False, False, True, True, False], [False, False, False, True, False, False, False, False, False], 'When this card enters play, place 6 Clue tokens on it. Any player may spend Clue tokens during the Arkham Encounter Phase while in the Easttown streets to discard Clue tokens from this card on a 1-for-1 basis. Ongoing Effect: Roll two dice at the end of every Mythos Phase (beginning the turn after it entered play). For every 1 or 2 rolled, place one Clue token on this card. Pass: If there are no Clue tokens on this card, return it to the box. Each player draws one unique item. Fail: If there are 10 Clue tokens on this card, return it to the box. All elder sign tokens are removed from the board.'] ,
	    ['Happy Days are Here Again', 'Arkham Horror', 'Environment', 'Urban', 'Woods', 'Historical Society', [False, True, False, False, True, True, False, False, False], [True, False, False, False, False, False, False, False, False], 'Due to the renewed prosperity that has come to Arkham, the terror level cannot increase.'] ,
	    ['Heat Wave', 'Arkham Horror', 'Environment', 'Weather', 'Woods', 'Independence Square', [False, False, False, False, True, True, False, False, False], [True, False, False, False, False, False, False, False, False], 'Fight checks in Arkham are made at a -1 penalty. Lore checks in Arkham are made at a +1 bonus. Fire Vampires have their toughness increased by 1.'] ,
	    ['Horror at Groundbreaking!', 'Arkham Horror', 'Headline', 'NULL', 'Historical Society', 'Silver Twilight Lodge', [False, False, True, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, True], 'An ancient stone is disturbed by the construction, releasing 2 monsters into the Miskatonic U. streets.'] ,
	    ['Icy Conditions', 'Arkham Horror', 'Environment', 'Weather', 'Historical Society', 'Silver Twilight Lodge', [False, False, False, False, False, False, False, False, True], [False, False, True, False, False, False, False, False, False], 'Investigators receive 1 less movement point during the Movement Phase. Fast Monsters move like normal monsters.'] ,
	    ['Ill Wind Grips Arkham!', 'Arkham Horror', 'Headline', 'NULL', 'Graveyard', 'Unvisited Isle', [False, False, False, True, False, False, False, False, False], [False, True, False, False, False, False, True, True, False], 'The first player must pass a Luck (-1) check or be Cursed.'] ,
	    ['Lodge Member Held for Questioning!', 'Arkham Horror', 'Headline', 'NULL', 'Black Cave', "Hibb's Roadhouse", [True, False, False, False, False, False, False, False, False], [False, False, False, False, True, True, False, False, False], 'A Silver Lodge ritual lets 2 monsters loose in the French Hill streets.'] ,
	    ['Lodge Members Watch the Night!', 'Arkham Horror', 'Headline', 'NULL', 'Unvisited Isle', 'Science Building', [True, False, False, False, False, False, False, False, False], [False, False, False, False, True, True, False, False, False], 'All monsters in the French Hill streets or locations are returned to the cup.'] ,
	    ['Manhunt in Arkham!', 'Arkham Horror', 'Headline', 'NULL', 'Woods', 'Independence Square', [False, True, False, False, False, False, True, True, False], [False, False, False, True, False, False, False, False, False], 'All monsters in locations are returned to the cup.'] ,
	    ['Merchants March on Crime!', 'Arkham Horror', 'Headline', 'NULL', 'Independence Square', 'The Unnamable', [True, False, False, False, False, False, False, False, False], [False, False, False, False, True, True, False, False, False], 'All monsters in the Merchant Dist. streets or locations are returned to the cup.'] ,
	    ['Miskatonic Arctic Expedition Returns!', 'Arkham Horror', 'Headline', 'NULL', "Hibb's Roadhouse", 'Independence Square', [False, False, True, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, True], 'Any Elder Things previously claimed as monster trophies by players return to life and are placed in the River Docks.'] ,
	    ['Missing People Return!', 'Arkham Horror', 'Headline', 'NULL', 'The Unnamable', 'Woods', [False, True, False, False, False, False, True, True, False], [False, False, False, True, False, False, False, False, False], 'All investigators currently lost in time and space immediately return to Arkham, appearing in a street or location of their choice.'] ,
	    ['No One Can Help You Now', 'Arkham Horror', 'Environment', 'Mystic', 'The Unnamable', 'Woods', [False, False, False, False, False, False, False, False, True], [False, False, True, False, False, False, False, False, False], 'Gates cannot be sealed, although they can still be closed.'] ,
	    ["Noden's Favor", 'Arkham Horror', 'Environment', 'Mystic', 'The Witch House', 'Black Cave', [False, True, False, False, False, False, True, True, False], [False, False, False, True, False, False, False, False, False], 'It costs 2 fewer Clue tokens to seal gates.'] ,
	    ['Picnickers Panic!', 'Arkham Horror', 'Headline', 'NULL', 'Unvisited Isle', 'Science Building', [False, False, True, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, True], 'A careless picnicker unleashes 2 monsters on the Downtown streets.'] ,
	    ['Planetary Alignment', 'Arkham Horror', 'Environment', 'Mystic', 'The Witch House', 'Black Cave', [False, False, False, False, True, True, False, False, False], [True, False, False, False, False, False, False, False, False], 'Thanks to the mystic energy generated by the planetary alignment, all Spells have a Sanity cost of 0.'] ,
	    ['Police Step Up Patrols in Northside!', 'Arkham Horror', 'Headline', 'NULL', 'Silver Twilight Lodge', 'Graveyard', [True, False, False, False, False, False, False, False, False], [False, False, False, False, True, True, False, False, False], 'All monsters in the Northside streets or locations are returned to the cup.'] ,
	    ['Private Security Hired in Uptown!', 'Arkham Horror', 'Headline', 'NULL', 'Woods', 'Historical Society', [True, False, False, False, False, False, False, False, False], [False, False, False, False, True, True, False, False, False], 'All monsters in the Uptown streets or locations are returned to the cup.'] ,
	    ['Raining Cats and Dogs', 'Arkham Horror', 'Environment', 'Weather', "Hibb's Roadhouse", 'Independence Square', [False, False, False, False, False, False, False, False, True], [False, False, True, False, False, False, False, False, False], 'Speed checks in Arkham are made at a -1 penalty, and players receive one less movement point during the Movement Phase. Sneak checks in Arkham are made at a +1 bonus. Return any Fire Vampires in play to the cup. If a Fire Vampire enters play, return it to the cup and draw a different monster.'] ,
	    ['Rivertown Residents Take Back Street!', 'Arkham Horror', 'Headline', 'NULL', 'The Witch House', 'Black Cave', [True, False, False, False, False, False, False, False, False], [False, False, False, False, True, True, False, False, False], 'All monsters in the Rivertown streets or locations are returned to the cup.'] ,
	    ["R'Lyeh Rising", 'Arkham Horror', 'Environment', 'Mystic', 'Woods', 'Historical Society', [False, True, False, False, False, False, True, True, False], [False, False, False, True, False, False, False, False, False], "Star Spawn and Maniacs have their toughness increased by 1. The difficulty to seal or close gates to R'lyeh is increased by 1."] ,
	    ['Scientist Warns of Dimensional Rift!', 'Arkham Horror', 'Headline', 'NULL', 'Unvisited Isle', 'Science Building', [False, False, False, True, False, False, False, False, False], [False, True, False, False, False, False, True, True, False], 'All Dimensional Shamblers and Hounds of Tindalos are returned to the cup. If one or more monster is returned to the cup, raise the terror level by 1.'] ,
	    ['Sheldon Gang Turns to Police for Aid!', 'Arkham Horror', 'Headline', 'NULL', 'Graveyard', 'Unvisited Isle', [True, False, False, False, False, False, False, False, False], [False, False, False, False, True, True, False, False, False], 'The Sheldon Gang disturbs a burial mound, releasing 2 monsters into the Uptown Streets.'] ,
	    ['Slum Murders Continue!', 'Arkham Horror', 'Headline', 'NULL', 'Woods', 'Historical Society', [False, False, True, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, True], 'An old basement is opened, releasing 2 monsters into the Easttown Streets.'] ,
	    ['Solar Eclipse', 'Arkham Horror', 'Environment', 'Mystic', 'Graveyard', 'Unvisited Isle', [False, False, False, False, True, True, False, False, False], [True, False, False, False, False, False, False, False, False], 'Due to the interference of the solar eclipse, no spells may be cast.'] ,
	    ['Southside Strangler Suspected!', 'Arkham Horror', 'Headline', 'NULL', 'Woods', 'Historical Society', [True, False, False, False, False, False, False, False, False], [False, False, False, False, True, True, False, False, False], 'However, the press is mistaken, and the murders were caused by 2 monsters that are released into the Southside streets.'] ,
	    ['Strange Lights on Campus!', 'Arkham Horror', 'Headline', 'NULL', 'Woods', 'Historical Society', [False, False, False, True, False, False, False, False, False], [False, True, False, False, False, False, True, True, False], 'The Library, Administration Building and Science Building are all closed until the end of next turn. Leave this card in play until then to indicate this.'] ,
	    ['Strange Power Flux Plagues City!', 'Arkham Horror', 'Headline', 'NULL', 'Independence Square', 'The Unnamable', [False, True, False, False, False, False, True, True, False], [False, False, False, True, False, False, False, False, False], 'All investigators in Other World areas may immediately return to Arkham.'] ,
	    ['Strange Tremors Cease!', 'Arkham Horror', 'Headline', 'NULL', 'Independence Square', 'The Unnamable', [False, False, False, True, False, False, False, False, False], [False, True, False, False, False, False, True, True, False], 'All Chthonians and Dholes in Arkham are returned to the cup. If at least one monster returns to the cup, raise the terror level by 1.'] ,
	    ['Sunny and Clear', 'Arkham Horror', 'Environment', 'Weather', 'Black Cave', "Hibb's Roadhouse", [False, False, False, False, False, False, False, False, True], [False, False, True, False, False, False, False, False, False], 'Sneak checks in Arkham are made at a -1 penalty. Will checks in Arkham are made at a +1 bonus. If the Haunter of the Dark is in play, return it to the cup. If the Hunter in Darkness enters play, return it to the cup and draw a different monster.'] ,
	    ['Temperence Fever Sweeps City', 'Arkham Horror', 'Headline', 'NULL', 'The Witch House', 'Black Cave', [False, False, False, True, False, False, False, False, False], [False, True, False, False, False, False, True, True, False], "Any investigator with Whiskey must pass a Sneak (-1) check or get arrested and taken to the Police Station. If this occurs, they must discard their Whiskey. In addition, Hibb's Roadhouse is closed until the end of next turn. Leave this card in play until then to indicate this."] ,
	    ['Terror at the Train Station!', 'Arkham Horror', 'Headline', 'NULL', 'The Witch House', 'Black Cave', [False, False, True, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, True], 'A rusty train arrives in Arkham, disgorging 2 monsters into the Northside streets.'] ,
	    ['The Chill of the Grave', 'Arkham Horror', 'Environment', 'Mystic', 'Unvisited Isle', 'Science Building', [False, False, False, False, False, False, False, False, True], [False, False, True, False, False, False, False, False, False], 'All Undead monsters have their toughness increased by 1.'] ,
	    ['The Festival', 'Arkham Horror', 'Environment', 'Urban', 'Woods', 'Historical Society', [False, False, False, False, False, False, False, False, True], [False, False, True, False, False, False, False, False, False], 'The festival has begun! Cultists and Byakhees have their toughness increased by 1.'] ,
	    ['The Great Ritual', 'Arkham Horror', 'Rumor', 'NULL', 'Graveyard', 'NULL', [False, True, False, False, False, False, True, True, False], [False, False, False, True, False, False, False, False, False], 'Ongoing Effect: Cultists, Witches, Warlocks, and High Priests have their toughness increased by 2 while this card is in play. Place 1 clue token on this card at the end of every Mythos Phase (beginning the turn after it entered play). Pass: If a single player discards 3 spells (4 if there are 5 or more players) while in the French Hill streets during the Arkham Encounters phase, return this card to the box. Each player gains 2 clue tokens. Fail: If there are ever 5 Clue tokens on this card, return it to the box. From now on, draw 2 Mythos cards each Mythos Phase. Ignore everything on the first card except for the gate opening. '] ,
	    ['The Man in Black', 'Arkham Horror', 'Environment', 'Mystic', 'The Witch House', 'Black Cave', [False, False, False, False, False, False, False, False, True], [False, False, True, False, False, False, False, False, False], 'Investigators who end their movement in the French Hill streets may deal with the Man in Black to gain power. They roll dice equal to their current Sanity and for every failed die, the lose 1 Sanity. If this reduces them to 0 Sanity, they are devoured and the player must start a new character. Otherwise, they gain 1 Clue token and draw 1 Spell.'] ,
	    ['The Southside Strangler Strikes', 'Arkham Horror', 'Rumor', 'NULL', 'Independence Square', 'NULL', [False, True, False, False, False, False, True, True, False], [False, False, False, True, False, False, False, False, False], "Ongoing Effect: Return one Ally from the Ally deck to the box at random at the end of every Mythos Phase while this card is in play (beginning the turn after it entered play). The Southside Strangler has struck again! Pass: If a single player discards 5 Clue tokens while in Ma's Boarding House during the Arkham Encounters Phase, return this card to the box. Each player receives a $5 reward from the police. Fail: If there are no more Allies to return to the box at the end of the Mythos Phase, return this card to the box. Each player must lower either their maximum Sanity or Stamina (their choice) by 1 for the rest of the game. "] ,
	    ['The Stars Are Right', 'Arkham Horror', 'Rumor', 'NULL', 'Science Building', 'NULL', [False, True, False, False, False, False, True, True, False], [False, False, False, True, False, False, False, False, False], "Ongoing Effect: Roll a die at the end of every Mythos Phase while this card is in play (beginning the turn after it enters play). On a 1 or 2, place one doom token on the ancient one's doom track. Pass: If a player discards an Ally card while in the Downtown streets during the Arkham Encounter Phase, return this card to the box. Each player draws 2 Common Items. Fail: If the Ancient One awakens, return this card to the box. "] ,
	    ['The Story Continues...', 'Arkham Horror', 'NULL', 'NULL', 'NULL', 'NULL', [False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False], '"I cannot remember, I must not remember what I saw on that dark and foreboding night.." Shuffle the mythos deck, being sure to include this card in it. After the deck is shuffled, draw a new mythos card for the turn. '] ,
	    ['The Terrible Experiment', 'Arkham Horror', 'Rumor', 'NULL', 'Unvisited Isle', 'NULL', [False, True, False, False, False, False, True, True, False], [False, False, False, True, False, False, False, False, False], 'When this card enters play, place 5 monsters from the cup on it. Any player may choose to fight one or more of these monsters while in the Miskatonic U. streets during the Arkham Encounter Phase. If defeated, they are claimed as monster trophies. These monsters do not move, are not considered on the board, and do not count against the monster limit. Ongoing Effect: Place a monster on this card at the end of every Mythos Phase (beginning the turn after it entered play). Pass: If there are no monsters on this card, return it to the box. Each player draws 1 Skill. Fail: If there are 8 monsters on this card, return it to the box. Raise the terror level to 10 and place the monsters that were on it in play in the Miskatonic U. streets. '] ,
	    ['Things of Darkness', 'Arkham Horror', 'Environment', 'Mystic', 'Silver Twilight Lodge', 'Graveyard', [False, False, False, False, True, True, False, False, False], [True, False, False, False, False, False, False, False, False], 'Ghouls, Formless Spawns, Shoggoths and Flying Polyps have their toughness increased by 1.'] ,
	    ['Vigilante Guards the Night!', 'Arkham Horror', 'Headline', 'NULL', 'The Unnamable', 'Woods', [True, False, False, False, False, False, False, False, False], [False, False, False, False, True, True, False, False, False], 'All monsters in the Downtown streets or locations are returned to the cup.'] ,
	    ['Witch Burning Anniversary!', 'Arkham Horror', 'Headline', 'NULL', 'Unvisited Isle', 'Science Building', [False, False, True, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, True], 'An ancient curse strikes Arkham, releasing 2 monsters into the Rivertown streets.'] ,
	    ['A Strange Plague', 'Arkham Horror', 'Environment', 'Mystic', 'Independence Square', 'The Unnamable', [False, False, False, False, True, True, False, False, False], [True, False, False, False, False, False, False, False, False], "Investigators cannot gain Stamina except by receiving medical care in St. Mary's Hospital (or from Vincent Lee)."] ,
	    ['Alien Technology', 'Arkham Horror', 'Environment', 'Urban', 'Unvisited Isle', 'Science Building', [False, False, False, False, True, True, False, False, False], [True, False, False, False, False, False, False, False, False], 'Mi-Go have their toughness increased by 2. If an investigator passes a Combat check against a Mi-Go, he draws 1 extra Unique Item.'] ,
	    ['All Quiet in Arkham!', 'Arkham Horror', 'Headline', 'NULL', 'Woods', 'Historical Society', [False, False, False, True, False, False, False, False, False], [False, True, False, False, False, False, True, True, False], 'Each player may pass a Luck (-1) check to be Blessed.'] ,
	    ['An Evil Fog', 'Arkham Horror', 'Environment', 'Weather', 'Graveyard', 'Unvisited Isle', [False, False, False, False, False, False, False, False, True], [False, False, True, False, False, False, False, False, False], 'Will checks in Arkham are made at a -1 penalty. Sneak checks in Arkham are made at a +1 bonus. Fliers do not move.'] ,
	]

Gates = [
	    ["Arkham Horror", "Another Dimension", [False, False, False, False, True, False, False, False, False], 0, ['investigator']],
	    ["Arkham Horror", "Great Hall of Celano", [False, False, False, False, False, False, True, False, False], -1, ['investigator']],
	    ["Arkham Horror", "Plateau of Leng", [False, False, False, False, False, True, False, False, False], -1, ['investigator']],
	    ["Arkham Horror", "R'lyeh", [False, False, False, False, False, False, False, False, True], -3, ['investigator']],
	    ["Arkham Horror", "The Abyss", [False, False, False, True, False, False, False, False, False], -2, ['investigator']],
	    ["Arkham Horror", "City of the Great Race", [False, True, False, False, False, False, False, False, False], 0, ['investigator']],
	    ["Arkham Horror", "The Dreamlands", [False, False, False, False, False, False, False, True, False], 1, ['investigator']],
	    ["Arkham Horror", "Yuggoth", [True, False, False, False, False, False, False, False, False], -2, ['investigator']]
	]

monsterscount = [
	    ["Arkham Horror", "Mi-Go", 3],
	    ["Arkham Horror", "Maniac", 3],
	    ["Arkham Horror", "Nightgaunt", 2],
	    ["Arkham Horror", "Shoggoth", 2],
	    ["Arkham Horror", "Star Spawn", 2],
	    ["Arkham Horror", "The Black Man", 1],
	    ["Arkham Horror", "The Bloated Woman", 1],
	    ["Arkham Horror", "The Dark Pharaoh", 1],
	    ["Arkham Horror", "Vampire", 1],
	    ["Arkham Horror", "Warlock", 2],
	    ["Arkham Horror", "Witch", 2],
	    ["Arkham Horror", "Zombie", 3],
	    ["Arkham Horror", "Byakhee", 3],
	    ["Arkham Horror", "Chthonian", 2],
	    ["Arkham Horror", "Cultist", 6],
	    ["Arkham Horror", "Dark Young", 3],
	    ["Arkham Horror", "Dhole", 1],
	    ["Arkham Horror", "Dimensional Shambler", 2],
	    ["Arkham Horror", "Elder Thing", 2],
	    ["Arkham Horror", "Fire Vampire", 2],
	    ["Arkham Horror", "Flying Polyp", 1],
	    ["Arkham Horror", "Formless Spawn", 2],
	    ["Arkham Horror", "Ghost", 3],
	    ["Arkham Horror", "Ghoul", 3],
	    ["Arkham Horror", "God of the Bloody Tongue", 1],
	    ["Arkham Horror", "Gug", 2],
	    ["Arkham Horror", "Haunter of the Dark", 1],
	    ["Arkham Horror", "High Priest", 1],
	    ["Arkham Horror", "Hound of Tindalos", 2]
	]