Locations = [
	    ["Arkham Horror", "Ye Olde Magick Shoppe"], 
	    ["Arkham Horror", "Woods"],
	    ["Arkham Horror", "Velma's Diner"],
	    ["Arkham Horror", "Unvisited Isle"],
	    ["Arkham Horror", "Train Station"],
	    ["Arkham Horror", "The Witch House"],
	    ["Arkham Horror", "The Unnamable"],
	    ["Arkham Horror", "St. Mary's Hospital"],
	    ["Arkham Horror", "South Church"],
	    ["Arkham Horror", "Silver Twilight Lodge"],
	    ["Arkham Horror", "Science Building"],
	    ["Arkham Horror", "River Docks"],
	    ["Arkham Horror", "Police Station"],
	    ["Arkham Horror", "Newspaper"],
	    ["Arkham Horror", "Ma's Boarding House"],
	    ["Arkham Horror", "Library"],
	    ["Arkham Horror", "Inner Sanctum"],
	    ["Arkham Horror", "Independence Square"],
	    ["Arkham Horror", "Administration Building"],
	    ["Arkham Horror", "Arkham Asylum"],
	    ["Arkham Horror", "Bank of Arkham"],
	    ["Arkham Horror", "Black Cave"],
	    ["Arkham Horror", "Curiositie Shoppe"],
	    ["Arkham Horror", "General Store"],
	    ["Arkham Horror", "Graveyard"],
	    ["Arkham Horror", "Hibb's Roadhouse"],
	    ["Arkham Horror", "Historical Society"],
	    ["Arkham Horror", "Northside"],
	    ["Arkham Horror", "Downtown"],
	    ["Arkham Horror", "Easttown"],
	    ["Arkham Horror", "Rivertown"],
	    ["Arkham Horror", "Miskatonic University"],
	    ["Arkham Horror", "French Hill"],
	    ["Arkham Horror", "Uptown"],
	    ["Arkham Horror", "Southside"],
	    ["Arkham Horror", "Merchant District"],
	]

connections = [
	    ["Ye Olde Magick Shoppe", {"Uptown" : ['black', 'white'] }], 
	    ["Woods", {"Uptown" : ['black', 'white'] }],
	    ["Velma's Diner", {"Easttown" : ['black', 'white'] }],
	    ["Unvisited Isle", {"Merchant District" : ['black', 'white'] }],
	    ["Train Station", {"Northside" : ['black', 'white'] }],
	    ["The Witch House", {"French Hill" : ['black', 'white'] }],
	    ["The Unnamable", {"Merchant District" : ['black', 'white'] }],
	    ["St. Mary's Hospital", {"Uptown" : ['black', 'white'] }],
	    ["South Church", {"Southside" : ['black', 'white'] }],
	    ["Silver Twilight Lodge", {"French Hill" : ['black', 'white'] }],
	    ["Science Building", {"Miskatonic University" : ['black', 'white'] }],
	    ["River Docks", {"Merchant District" : ['black', 'white'] }],
	    ["Police Station", {"Easttown" : ['black', 'white'] }],
	    ["Newspaper", {"Northside" : ['black', 'white'] }],
	    ["Ma's Boarding House", {"Southside" : ['black', 'white'] }],
	    ["Library", {"Miskatonic University" : ['black', 'white'] }],
	    ["Inner Sanctum", {"French Hill" : ['black', 'white'] }],
	    ["Independence Square", {"Downtown" : ['black', 'white'] }],
	    ["Administration Building", {"Miskatonic University" : ['black', 'white'] }],
	    ["Arkham Asylum", {"Downtown" : ['black', 'white'] }],
	    ["Bank of Arkham", {"Downtown" : ['black', 'white'] }],
	    ["Black Cave", {"Rivertown" : ['black', 'white'] }],
	    ["Curiositie Shoppe", {"Northside" : ['black', 'white'] }],
	    ["General Store", {"Rivertown" : ['black', 'white'] }],
	    ["Graveyard", {"Rivertown" : ['black', 'white'] }],
	    ["Hibb's Roadhouse", {"Easttown" : ['black', 'white'] }],
	    ["Historical Society", {"Southside" : ['black', 'white'] }],
	    ["Northside", {"Downtown" : ['white'], "Merchant District" : ['black'] }],
	    ["Downtown", {"Merchant District": [], "Easttown" : ['white'], "Northside" : ['black'] }],
	    ["Easttown", {"Rivertown" : ['white'], "Downtown" : ['black'] }],
	    ["Rivertown", {"Merchant District": [], "French Hill" : ['white'], "Easttown" : ['black'] }],
	    ["Miskatonic University", {"Merchant District" : ['white'], "Uptown" : ['black'] }],
	    ["French Hill", {"French Hill" : ['white'], "Easttown" : ['black'] }],
	    ["Uptown", {"Miskatonic University" : ['white'], "Southside" : ['black'] }],
	    ["Southside", {"Uptown" : ['white'], "French Hill" : ['black'] }],
	    ["Merchant District", {"Downtown": [], "Rivertown": [], "Northside" : ['white'], "Miskatonic University" : ['black'] }],
	]

Investigatordata = [
		["Agnes", "Baker", "Waitress", "Velma's Diner", 5, 5, 2],
		["\"Ashcan\"", "Pete", "Drifter", "River Docks", 4, 6, 1],
		["Jenny", "Barnes", "Dilettante", "Train Station", 6, 4, 1],
		["Harvey", "Walters", "Professor", "Administration Building", 7, 3, 2],
	]

Otherworlds = [
	    ["Arkham Horror", "Another Dimension", ["Blue", "Green", "Red", "Yellow"]],
	    ["Arkham Horror", "Great Hall of Celano", ["Blue", "Green"]],
	    ["Arkham Horror", "Plateau of Leng", ["Green", "Red"]],
	    ["Arkham Horror", "R'lyeh", ["Red", "Yellow"]],
	    ["Arkham Horror", "The Abyss", ["Blue","Red"]],
	    ["Arkham Horror", "City of the Great Race", ["Green", "Yellow"]],
	    ["Arkham Horror", "The Dreamlands", ["Blue", "Green", "Red", "Yellow"]],
	    ["Arkham Horror", "Yuggoth", ["Blue", "Yellow"]]
	]